### ISSUE TITLE
Incorrect jQuery dependency.

### ISSUE THREAD

**Issue by chris-ls** [ServiceStack/ss-utils#1]
The current jQuery dependency is specified as `"jquery": ">=2.0.0"` which now causes jQuery 3 to be installed with ss-utils.
[ss-utils: line 540](https://github.com/ServiceStack/ss-utils/blob/8afa8c96e797bbb5f25a9895e641e953cf837d9d/ss-utils.js#L540) uses unload() which has been completely removed from jQuery 3 and throws an error.

Solutions:

Change jQuery dependency to `"jquery": "^2.0.0"`
OR
2. Change `.unload(function(){})` to `.on('unload', function(){})`

**Comment by justwright** [comment]
Are there any plans to fix this in the foreseeable future?

**Comment by mythz** [comment]
apologies notifications on this repo fell of the radar, I've just updated it to the latest version in this commit: https://github.com/ServiceStack/ss-utils/commit/dac01d33109f2600453885b81bafca17fc643260

Which is now available on npm from **v0.1.7**

**Comment by justwright** [comment]
No worries, thank you for addressing it!
