### ISSUE TITLE
ajaxSubmit not working with file

### ISSUE THREAD

**Issue by synry63** [ServiceStack/ss-utils#2]
Just wondering, the function ajaxSubmit. Example on servicestack
http://docs.servicestack.net/ss-utils-js#ajaxsubmit

The function does not work with file input right ?

**Comment by mythz** [comment]
No you'll need to use an Ajax File Uploader, there's an example of using a [FineUploader in HttpBenchmarks demo](https://github.com/ServiceStackApps/HttpBenchmarks#fine-uploader).

There's also a new [HTML5 File API](https://developer.mozilla.org/en-US/docs/Using_files_from_web_applications) you can use to upload files now.
