### ISSUE TITLE
Uncaught TypeError: Cannot assign to read only property 'target' of object '#<MessageEvent>'

### ISSUE THREAD

**Issue by justwright** [ServiceStack/ss-utils#3]
Line causing console error: https://github.com/ServiceStack/ss-utils/blob/master/ss-utils.js#L511

![image](https://cloud.githubusercontent.com/assets/1421916/25754294/876e190e-3173-11e7-95cf-66380c12ff5f.png)

**Comment by justwright** [comment]
For reference: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Read-only

**Comment by mythz** [comment]
How can we repro this error? Is this only happening in Firefox or Chrome as well?

**Comment by labilbe** [comment]
Also have same problem.
Works on IE11 and Edge.
Does not work on Chrome, Firefox and Opera.

I am using ServiceStack v4.5.12, jQuery v3.1.1.

**Comment by mythz** [comment]
I've renamed the property to `$target` in this commit: https://github.com/ServiceStack/ss-utils/commit/f41e1ce9334b16caeebf0145a4b438d46fe878d7

This is now available on npm from v0.1.9

**Comment by labilbe** [comment]
Thank you very much mythz!
