### ISSUE TITLE
Unexpected url returned from $.ss.createUrl() method

### ISSUE THREAD

**Issue by labilbe** [ServiceStack/ss-utils#4]
Tested with the following:
`var previewStringUrl = $.ss.createUrl("/api/json/reply/PreviewStringLabel?", {scale:2,label:textToPrint,fontEmSize:fontSize,labelFormatId:labelFormat,fontName:fontName,bold:bold});
`

returned value is:
`api/json/reply/PreviewStringLabel?&scale=2&label=Exemple&fontEmSize=16&labelFormatId=57.5%20mm%20x%2035%20mm&fontName=Arial&bold=false`

I was expecting `/api/...` instead of `api/...`

Is it a bug or is it something I have misunderstood?

**Comment by mythz** [comment]
fixed in [this commit](https://github.com/ServiceStack/ss-utils/commit/ad91bba8975bdd947a58ccd93d8ead76ca9829b3) which is now available from v0.2.0 that's on npm.
