### ISSUE TITLE
Reconnecting to server strips out part of url

### ISSUE THREAD

**Issue by marialomidze** [ServiceStack/ss-utils#5]
I am trying to create an eventSource with url that contains session id, which looks something like this: 
`new EventSource("https://..../event-stream?channels=some-channel&ss-id=111")`
However I am running into an issue when event-stream is resent (when trying to reconnect to server). In ss-utils a new eventSource is created within reconnectServerEvents function: 
`var es = new EventSource(opt.url || $.ss.eventSourceUrl || hold.url);`. 

At this point eventSourceUrl contains some value, so a new event-stream is sent using eventSourceUrl as url. eventSourceUrl is earlier set to `url.substring(0, Math.min(url.indexOf('?'), url.length)) + "?channels=" + channels.join(',')`, which evaluates to something like this: `https://..../event-stream?channels=some-channel`. This causes ss-id to be stripped out when reconnecting to server. 

hold.url on the other hand contains the full url that I am trying to use: `var hold = $.ss.eventSource;`. opt.url is always empty (opt only contains string "error").

I am confused about the purpose of eventSourceUrl, and how to keep the original url that contains ss-id when reconnecting.

**Comment by mythz** [comment]
Should be resolved with this commit: https://github.com/ServiceStack/ss-utils/commit/7fb3e1ce2f3f81d3a42fefd9670b3dbf64d5389e which is now on npm in ss-utils v0.2.1 or available in [ServiceStack v5 that's now available on MyGet](https://forums.servicestack.net/t/myget-pre-release-packages-upgraded-to-v5/4749/1).
