### ISSUE TITLE
$.unload was deprecated since 1.8 and has been removed in 3.x

### ISSUE THREAD

**Issue by ricardobrandao** [ServiceStack/ss-utils#6]
ss-utils doesn't work with jQuery >3.x because the unload method has been deprecated. The release notes says the following:

> ## Removed deprecated event aliases
> .load, .unload, and .error, deprecated since jQuery 1.8, are no more. Use .on() to register listeners.

**Comment by mythz** [comment]
The latest version already uses `.on("unload")` 
https://github.com/ServiceStack/ss-utils/blob/master/ss-utils.js#L561
