### ISSUE TITLE
window on unload post event is being canceled

### ISSUE THREAD

**Issue by ASH-Maan** [ServiceStack/ss-utils#7]
Referring to [this question](https://stackoverflow.com/questions/3138498/window-unload-wait-for-ajax-call-to-finish-before-leaving-a-webpage), I have an issue where the browser is destroying the DOM object and canceling the xhr request.

This code generating this issue:
```javascript
if (opt.unRegisterUrl) {
  $(window).on("unload", function () {
    $.post(opt.unRegisterUrl, null, function (r) { });
   });
}
```
The fix:
```javascript
if (opt.unRegisterUrl) {
  $(window).on("unload", function () {
    $.ajax({
      type: 'POST',
      async: false,
      url: opt.unRegisterUrl
    });
  });
}
```
setting async to false will tell the browser to wait for the request to finish first.

**Comment by mythz** [comment]
Thanks for the pointer, resolved in this commit: https://github.com/ServiceStack/ss-utils/commit/5047567f0f1b9cfe6f00580e3382bca970bb1942

**Comment by ASH-Maan** [comment]
@mythz Thanks for fixing this. Will there be a new version update pushed to npm for this?
